### ISSUE TITLE
Can you help me

### ISSUE THREAD

**Issue by MyMiMang** [yangchris11/samurai#32]
(base) dd@DESKTOP-CFQBGFO:~$ python scripts/demo.py --video_path Video/1.mp4 --txt_path Video/frame_bbox.txt
SAMURAI mode: True
Traceback (most recent call last):
  File "/home/dd/scripts/demo.py", line 120, in <module>
    main(args)
  File "/home/dd/scripts/demo.py", line 44, in main
    predictor = build_sam2_video_predictor(model_cfg, args.model_path, device="cuda:0")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/sam2/sam2/build_sam.py", line 130, in build_sam2_video_predictor
    _load_checkpoint(model, ckpt_path)
  File "/home/dd/sam2/sam2/build_sam.py", line 159, in _load_checkpoint
    sd = torch.load(ckpt_path, map_location="cpu", weights_only=True)["model"]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/miniconda3/lib/python3.12/site-packages/torch/serialization.py", line 1326, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/miniconda3/lib/python3.12/site-packages/torch/serialization.py", line 671, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
(base) dd@DESKTOP-CFQBGFO:~$

**Comment by Hyul48** [comment]
may use torch.load before fully downloaded

**Comment by zhyjiang** [comment]
Did you run the script
```
cd checkpoints && \
./download_ckpts.sh && \
cd ..
```
under `sam2` folder?

**Comment by MyMiMang** [comment]
Yes In the folder sam2
![2](https://github.com/user-attachments/assets/3c42b6a7-d6b1-4bb3-930a-2415c8c27c6c)
![3](https://github.com/user-attachments/assets/eafa2c0e-5e86-47b9-9483-0f669450456f)

**Comment by zhyjiang** [comment]
These are what I got
```
/samurai$ ll sam2/checkpoints/
total 1525540
drwxrwxr-x  2 zhongyuj zhongyuj      4096 Nov 25 11:58 ./
drwxrwxr-x 10 zhongyuj zhongyuj      4096 Nov 25 11:04 ../
-rwxrwxr-x  1 zhongyuj zhongyuj      2612 Nov 25 11:04 download_ckpts.sh*
-rw-rw-r--  1 zhongyuj zhongyuj 323606802 Sep 28 20:15 sam2.1_hiera_base_plus.pt
-rw-rw-r--  1 zhongyuj zhongyuj 898083611 Sep 28 20:15 sam2.1_hiera_large.pt
-rw-rw-r--  1 zhongyuj zhongyuj 184416285 Sep 28 20:14 sam2.1_hiera_small.pt
-rw-rw-r--  1 zhongyuj zhongyuj 156008466 Sep 28 20:13 sam2.1_hiera_tiny.pt
```

Maybe you can delete all the checkpoints and re-download

**Comment by MyMiMang** [comment]
> 这些是我得到的
> 
> ```
> /samurai$ ll sam2/checkpoints/
> total 1525540
> drwxrwxr-x  2 zhongyuj zhongyuj      4096 Nov 25 11:58 ./
> drwxrwxr-x 10 zhongyuj zhongyuj      4096 Nov 25 11:04 ../
> -rwxrwxr-x  1 zhongyuj zhongyuj      2612 Nov 25 11:04 download_ckpts.sh*
> -rw-rw-r--  1 zhongyuj zhongyuj 323606802 Sep 28 20:15 sam2.1_hiera_base_plus.pt
> -rw-rw-r--  1 zhongyuj zhongyuj 898083611 Sep 28 20:15 sam2.1_hiera_large.pt
> -rw-rw-r--  1 zhongyuj zhongyuj 184416285 Sep 28 20:14 sam2.1_hiera_small.pt
> -rw-rw-r--  1 zhongyuj zhongyuj 156008466 Sep 28 20:13 sam2.1_hiera_tiny.pt
> ```
> 
> 也许你可以删除所有检查点并重新下载
![4](https://github.com/user-attachments/assets/3a5d74c9-3112-4a0c-9922-b342f1acc79d)

It looks like it worked. How do I run this program to matting videos

**Comment by zhyjiang** [comment]
If you want to get the mask of each frame, you may need to hack demo.py to save all the generated masks.

**Comment by wadave** [comment]
I got this error:
~/remote_ws/projects/samurai$ python scripts/demo.py --video_path data/final_video_6_zoomed.mp4 --txt_path data/first_box.txt
SAMURAI mode: True
Traceback (most recent call last):
  File "/usr/local/google/home/wangdave/remote_ws/projects/samurai/scripts/demo.py", line 122, in <module>
    main(args)
  File "/usr/local/google/home/wangdave/remote_ws/projects/samurai/scripts/demo.py", line 44, in main
    predictor = build_sam2_video_predictor(model_cfg, args.model_path, device="cuda:0")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/wangdave/remote_ws/projects/samurai/sam2/sam2/build_sam.py", line 131, in build_sam2_video_predictor
    model = model.to(device)
            ^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/wangdave/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1340, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/wangdave/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  File "/usr/local/google/home/wangdave/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  File "/usr/local/google/home/wangdave/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/usr/local/google/home/wangdave/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 927, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/usr/local/google/home/wangdave/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1326, in convert
    return t.to(
           ^^^^^
  File "/usr/local/google/home/wangdave/miniconda3/lib/python3.12/site-packages/torch/cuda/__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
**AssertionError: Torch not compiled with CUDA `enabled`**

**Comment by zhyjiang** [comment]
SAMURAI does not support CPU inference. You need to install pytorch with cuda enabled.

**Comment by wadave** [comment]
I changed to this:
if torch.cuda.is_available():
        device = torch.device("cuda")
    elif torch.backends.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")
    print(f"using device: {device}")
    
    if device.type == "cuda":
        # use bfloat16 for the entire notebook
        torch.autocast("cuda", dtype=torch.bfloat16).__enter__()
        # turn on tfloat32 for Ampere GPUs (https://pytorch.org/docs/stable/notes/cuda.html#tensorfloat-32-tf32-on-ampere-devices)
        if torch.cuda.get_device_properties(0).major >= 8:
            torch.backends.cuda.matmul.allow_tf32 = True
            torch.backends.cudnn.allow_tf32 = True
    elif device.type == "mps":
        print(
            "\nSupport for MPS devices is preliminary. SAM 2 is trained with CUDA and might "
            "give numerically different outputs and sometimes degraded performance on MPS. "
            "See e.g. https://github.com/pytorch/pytorch/issues/84936 for a discussion."
        )
    predictor = build_sam2_video_predictor(model_cfg, args.model_path, device=device)

**Comment by wadave** [comment]
It seems to be working.
