### ISSUE TITLE
Nuke Launch Error

### ISSUE THREAD

**Issue by j89012g** [yangchris11/samurai#76]
I followed every steps in the description for installation, yet I encountered the following error: 

NukeX 15.0v4, 64 bit, built Feb  6 2024.
Copyright (c) 2024 The Foundry Visionmongers Ltd.  All Rights Reserved.
Licence expires on: 2025/3/17

Traceback (most recent call last):
  File "C:/Program Files/Nuke15.0v4/plugins/NukeSamurai/menu.py", line 4, in <module>
    from scripts.nuke_samurai import CreateSamuraiNode, UpdatePath, GenerateMask, BoundingBox, InputInfos
  File "C:\Program Files\Nuke15.0v4\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Program Files/Nuke15.0v4/plugins/NukeSamurai\scripts\nuke_samurai.py", line 6, in <module>
    import torch
  File "C:\Program Files\Nuke15.0v4\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users/USER/AppData/Local/Programs/Python/Python310/Lib/site-packages\torch\__init__.py", line 132, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "C:\Users/USER/AppData/Local/Programs/Python/Python310/Lib/site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.

**Comment by yangchris11** [comment]
Please open the issue at the corresponding repo.
